language: node_js
addons:
  sauce_connect: true
node_js:
  - "6.2.0"
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - npm run lint
  - npm run unit-test
  - npm run sauce-labs
  - pkill node
